---
version: '3.7'

services:

  base: &base
    build:
      context: .
    working_dir: /app
    volumes:
      - ".:/app"
      - /app/node_modules

  sh:
    <<: *base
    entrypoint:
      - bash

  selenium-hub:
    image: selenium/hub:3.9.1
    environment:
      GRID_BROWSER_TIMEOUT: 120000
      GRID_NEW_SESSION_WAIT_TIMEOUT: 8000
      GRID_NODE_POLLING: 300
      GRID_TIMEOUT: 120000
      JAVA_OPTS: -Xmx512m
    ports:
     - "4444:4444"
    networks:
      - nightwatch-docker-grid-network

  nightwatch:
    <<: *base
    command: yarn test
    environment: &HubENV
      HUB_HOST: selenium-hub
      HUB_PORT: 4444
    depends_on:
      - selenium-hub
      - chrome
      - firefox
    networks:
      - nightwatch-docker-grid-network

  chrome:
    image: selenium/node-chrome:3.9.1
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
    environment:
      <<: *HubENV
    volumes:
      - /dev/shm:/dev/shm

  chrome-debug:
    image: selenium/node-chrome-debug:3.9.1
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
    environment:
      <<: *HubENV
    ports:
      - "5900:5900"
    networks:
      - nightwatch-docker-grid-network

  firefox:
    image: selenium/node-firefox:3.9.1
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
    environment:
      <<: *HubENV
    networks:
      - nightwatch-docker-grid-network

  firefox-debug:
    image: selenium/node-firefox-debug:3.9.1
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
    environment:
      <<: *HubENV
    ports:
      - "5901:5900"
    networks:
      - nightwatch-docker-grid-network

networks:
  nightwatch-docker-grid-network:
    driver: bridge
    name: nightwatch-docker-grid-network
