---
version: '3.7'

services:

  base: &base
    build:
      context: .
    working_dir: /app
    volumes:
      - ".:/app"
      - /app/node_modules

  sh:
    <<: *base
    entrypoint:
      - bash

  hub:
    image: selenium/hub:3.9.1
    environment:
      GRID_BROWSER_TIMEOUT: 120000
      GRID_NEW_SESSION_WAIT_TIMEOUT: 8000
      GRID_NODE_POLLING: 300
      GRID_TIMEOUT: 120000
    networks:
      - nightwatch-docker-grid-network
    logging: &LOG
      options:
        max-file: '5'
        max-size: 1m

  nightwatch:
    <<: *base
    command: yarn test
    environment: &SELENIUM_NODE_ENV
      HUB_PORT_4444_TCP_ADDR: hub
    depends_on:
      - hub
      - chrome
      - firefox
    networks:
      - nightwatch-docker-grid-network
    logging: *LOG

  chrome:
    image: selenium/node-chrome:4.0.0
    environment:
      <<: *SELENIUM_NODE_ENV
    logging: *LOG

  chrome-debug:
    image: selenium/node-chrome-debug:3.9.1
    environment:
      <<: *SELENIUM_NODE_ENV
    ports:
      - "5900:5900"
    networks:
      - nightwatch-docker-grid-network
    logging: *LOG

  firefox:
    image: selenium/node-firefox:4.0.0
    environment:
      <<: *SELENIUM_NODE_ENV
    networks:
      - nightwatch-docker-grid-network
    logging: *LOG

  firefox-debug:
    image: selenium/node-firefox-debug:3.9.1
    environment:
      <<: *SELENIUM_NODE_ENV
    ports:
      - "5901:5900"
    networks:
      - nightwatch-docker-grid-network
    logging: *LOG

networks:
  nightwatch-docker-grid-network:
    driver: bridge
    name: nightwatch-docker-grid-network
